import Head from 'next/head'
import Image from 'next/image'

import styled from "styled-components";
import styles from "../styles/Home.module.css";

import Filter from "../components/Filter";
import HeroCarousel from "../components/HeroCarousel";
import Search from "../components/Search/index";
import Continue from "../components/Continue";
import Category from "../components/Category";
import Footer from "../components/Footer";
import BigCalendar from "../components/Calendars/BigCalendar";
import Calendars from "../components/Calendars";

export default function Home() {
  return (
    <Wrapper className={styles.container}>
      <Head>
        <title>Power over Pain | Surmonter sa douleur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <HeroCarousel />
        <Search />
        <Filter />
        <Continue />
        <Category />
        <Calendars />
        <Footer />
      </main>
    </Wrapper>
  );
}

const Wrapper = styled.div`
  display: flex;
  flex-direction: column;
  width: 100%;
  background: rgb(143, 189, 226);
  background: rgb(182, 216, 244);
  background: linear-gradient(
    337deg,
    rgba(182, 216, 244, 1) 0%,
    rgba(75, 112, 201, 1) 97%
  );
`;