import { useContext, useEffect } from "react";
import { CategoriesContext } from "../context/CategoriesContext";
import styled from "styled-components";
import styles from "../styles/Home.module.css";

import Head from "next/head";

import Filter from "../components/Filter";
import HeroCarousel from "../components/Hero/index";
import Continue from "../components/Continue";
import Category from "../components/Category";
import Footer from "../components/Footer";
import Calendars from "../components/Calendars";
import Layout from "../components/Layout";
import Trending from "../components/Trending/index";
import fetchAllData from "../lib/api";

export default function Home({
  categories,
  resources,
  hero,
  searchTerms,
  topics,
}) {
  // Set categories to context on component load
  // const { setCategories } = useContext(CategoriesContext);
  // useEffect(() => {
  //   setCategories(categories);
  // }, [setCategories, categories]);

  return (
    <Wrapper className={styles.container}>
      <Head>
        <title>Power over Pain | Surmonter sa douleur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Layout categories={categories} topics={topics} />
        <HeroCarousel hero={hero} />
        <Trending />
        <Filter resources={resources} searchTerms={searchTerms} />
        <Continue />
        <Category categories={categories} resources={resources} />
        <Calendars />
        <Footer />
      </main>
    </Wrapper>
  );
}

// Fetches all data via SSG
export async function getStaticProps() {
  return fetchAllData();
}

const Wrapper = styled.div`
  display: flex;
  flex-direction: column;
  width: 100%;
  background: rgb(143, 189, 226);
  background: rgb(182, 216, 244);
  background: linear-gradient(
    337deg,
    rgba(182, 216, 244, 1) 0%,
    rgba(75, 112, 201, 1) 97%
  );
`;
